on:
  push:
    branches:
      - published

name: Publish app to shinyapps.io

jobs:
  build-deploy:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # From https://github.com/r-lib/actions/tree/v2-branch/setup-r
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup renv
        uses: r-lib/actions/setup-renv@v2

      - name: Publish app to shinyapps.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='church-army', token='${{secrets.SHINYAPPS_TOKEN}}', secret='${{secrets.SHINYAPPS_SECRET}}')"
          Rscript -e "rsconnect::deployApp(appName = 'waterways-test')"
